server {
listen 80;
root /var/www/myphpapp;
index logout.php logout.html;
access_log /var/log/nginx/myphpapp_access.log;
error_log /var/log/nginx/myphpapp_error.log;
location / {
try_files $uri $uri/ /logout.php?$query_string;
}
location ~ \.php$ {
fastcgi_pass php:9000;
fastcgi_index logout.php;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
include fastcgi_params;
}
}